DELETE http://localhost:3001/api/blogs/64b77cadbf3e389493161c61
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFwb3dlcnMiLCJpZCI6IjY0YWQwYWZmODM2NzE1MzA2ZDkwYmY3MyIsImlhdCI6MTY4OTA2Nzk2NX0.FIuRoYkU0BNfa0nb44-swkEZLrUFA3gRaJ-_K5PxAEQ